[package]
name = "icons"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = "0.3.2"
dioxus-html = "0.3.1" 

[build-dependencies]
heck = "~0.4"
itertools = "~0.10"
scraper = "~0.12"
walkdir = "~2"

