[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
dioxus.workspace = true
dioxus-hooks.workspace = true
dioxus-router.workspace = true
dioxus-desktop = { workspace = true, features = ["transparent"] }
raw-window-handle.workspace = true
dioxus-core.workspace = true
fermi.workspace = true
kit.workspace = true
common.workspace = true
tokio-util.workspace = true
arboard.workspace = true
humansize.workspace = true
window-vibrancy.workspace = true
uuid.workspace = true
libloading.workspace = true
warp.workspace = true
warp-mp-ipfs.workspace = true
warp-rg-ipfs.workspace = true
warp-fs-ipfs.workspace = true
rfd.workspace = true
mime.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
either.workspace = true
base64.workspace = true
timeago.workspace = true
dirs.workspace = true
opener.workspace = true
open.workspace = true
wry.workspace = true
derive_more.workspace = true
colored.workspace = true
notify.workspace = true
rand.workspace = true
notify-rust.workspace = true
titlecase.workspace = true
tempfile.workspace = true
fdlimit.workspace = true
once_cell.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["full"] }
isolang.workspace = true
regex.workspace = true
image.workspace = true
clap = { workspace = true, features = ["derive"] }
fs_extra.workspace = true
walkdir.workspace = true
zip.workspace = true
filetime = "0.2.20"
reqwest = { version = "0.11", default-features=false, features = ["json", "rustls-tls", "stream"] }

[features]
fullscreen = ["wry/fullscreen"]
transparent = ["wry/transparent"]
tray = ["wry/tray"]
production_mode = ["common/production_mode"]

[build-dependencies]
glob = "0.3.0"
rustc_version = "0.4.0"
rsass = "0.26.0"
zip.workspace = true
walkdir.workspace = true