[package]
name = "egui-miniquad"
version = "0.1.0"
edition = "2021"

[dependencies]
miniquad = "0.3.12"
egui-miniquad = "0.12.0"
egui = { version = "0.19.0", features = ["bytemuck"] }
egui_demo_lib = { version = "0.19.0", default-features = false }