[package]
name = "gif_animation"
version = "0.1.0"
edition = "2021"

[dependencies]
gif = "0.11.0"
gif-dispose = "3.1.0"
rgb = "0.8.0"
image = "0.24.0"
macroquad = { git = "https://github.com/phR0ze/macroquad", rev = "9daaef8" }