[package]
name = "egui-miniquad_render_in_egui_win"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.21.1"
miniquad = "0.3.12"
egui-miniquad = "0.12.0"
egui = { version = "0.19.0", features = ["bytemuck"] }