[workspace]
members = [".", "macros"]

[workspace.package]
version = "0.1.0"

[package]
name = "include-more"
version = { workspace = true }
edition = "2021"

[dependencies]
include-more-macros = { path = "./macros" }
once_cell = "1.10.0"
