[package]
name = "thumbnails"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rivia-vfs = "0.2.0"
image = "0.24.0"
macroquad = { git = "https://github.com/phR0ze/macroquad", rev = "9daaef8" }