[package]
name = "static-loader-macros"
version.workspace = true
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.36"
quote = "1.0.15"
syn = { version = "2.0.15", features = ["full"] }
ignore = "0.4.16"
flume = { version = "0.10.12", default-features = false }